name: Go
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Build
      working-directory: ./app
      run: |
        GITHUB_SHA_SHORT=$(git rev-parse --short "$GITHUB_SHA")
        echo "GITHUB_SHA_SHORT=${GITHUB_SHA_SHORT}" >> $GITHUB_ENV
        GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build main.go
        zip function-${GITHUB_SHA_SHORT}.zip main
    - name: Store
      working-directory: ./app
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-west-2'
      run: |
        aws s3 cp ./function-${GITHUB_SHA_SHORT}.zip s3://crossplane-serverless/
    - name: update manifest
      run: |
        yq eval -i ".spec.bucketKey = \"crossplane-serverless/function-${GITHUB_SHA_SHORT}.zip\"" manifests/serverless-processor.yaml
    - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: update argocd manifest
          title: update argocd manifest 
          body:  update argocd manifest 
          branch: argocd-dev-manfiests
          base: main
          delete-branch: true
